#!/bin/bash

mkdir -p ca

CA_FILE=ca/ca.pem
CA_KEY_FILE=ca/ca-key.pem

openssl genrsa -aes256 -out $CA_KEY_FILE 2048
openssl req -new -x509 -days 365 -key $CA_KEY_FILE -sha256 -out $CA_FILE

echo Done!
ls -la ca
